# Site
name: "Late Bloomer Cycling"
title: "Late Bloomer Cycling"
description: "Travel, Food, and Friendship via Cycling. Fitness secondary."
logo: 'assets/images/logo_v2.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'G-RV38QGWM6E'
disqus: 'late-bloomer-cycling'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:categories/:year/:month/:day/:title
email: latebloomercycling@gmail.com
formspring: mjvjpaqn

# Authors
authors:
  vinny:
    name: Vinny
    display_name: Vinny
    avatar: 'assets/images/vinny-avatar.jpg'
    email: latebloomercycling@gmail.com
    web: https://www.vinnymarquez.com
    twitter: https://twitter.com/lakanbinimusic
    description: "Makes computers do sh*t for a living. Makes music, plays games, rolls on the mats, and cycles for fun. Started cycling in October 2020."
  dee:
    name: Dee
    display_name: Dee    
    avatar: 'assets/images/dee-avatar.jpg'
    email: latebloomercycling@gmail.com
    twitter: https://twitter.com/psychepomp
    description: "Quasi-cyclist, flower gatherer, dog spotter, fickle gear chooser, and silken tofu hunter. Started biking (for reals) Mar 2021."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
