# Site
name: "Late Bloomer Cycling"
title: "Late Bloomer Cycling"
description: "Travel, Food, and Friendship via Cycling. Fitness secondary."
logo: 'assets/images/logo_v2.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'G-RV38QGWM6E'
disqus: 'late-bloomer-cycling'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:categories/:year/:month/:day/:title
email: latebloomercycling@gmail.com
formspring: mjvjpaqn

# Groups
cyclists:
  vinny:
    name: vinny-marquez
    display_name: Vinny Marquez
    nickname: Vinny / ChuVi / Lakan Bini
    role: admin
    showProfile: true
    team: team-itim
    facebook: chuv13
    instagram: lakanbinimusic
    twitter: lakanbinimusic
    avatar: assets/images/vinny-avatar.jpg
    card-cover: assets/images/vinny-card.jpg
    cover: 'assets/images/groups/team-itim/vinny-cover.jpg'
    occupation: Software Developer / Test Automation Engineer
    description: "Makes computers do sh*t for a living. Makes music, plays games, rolls on the mats, and cycles for fun. Started cycling in October 2020."
    bikes:
      allez: 
        name: Stella
        make: Specialized
        model: Allez
        year: 2020
        photo: 'assets/images/stella.jpg'
        description: 'Shimano 105, RS11, GP5000 25c'
        status: operational
      redwood: 
        name: Pikel
        make: Poseidon
        model: Redwood
        year: 2021
        photo: 'assets/images/pikel.jpg'
        description: 'SRAM GX Lunar, SRAM Rival shifters, Ratio Technologies 1x12 Upgrade Kit, Token G23AR, Ritchey Venturemax v2, Wolftooth 40T Assymetric, PNW Coast Suspension Dropper Post'
        status: mid-build
  dennis:
    name: dennis-anaya
    display_name: Dennis Anaya
    nickname: Dennis
    role: contributor
    showProfile: false
    team: team-itim
    facebook: dennis.anaya.37
    instagram: dr.anaya
    avatar: assets/images/vinny-avatar.jpg
    card-cover: assets/images/dennis-card.jpg
    cover: 'assets/images/groups/team-itim/vinny-cover.jpg'
    occupation: Software Developer / Test Automation Engineer
    description: "Makes computers do sh*t for a living. Makes music, plays games, rolls on the mats, and cycles for fun. Started cycling in October 2020."
    bikes:
      allez: 
        name: Stella
        make: Specialized
        model: Allez
        year: 2020
        photo: 'assets/images/stella.jpg'
        description: 'Shimano 105, RS11, GP5000 25c'
        status: operational
  john:
    name: john-patricio
    display_name: John Patricio
    nickname: John
    role: contributor
    showProfile: false
    team: team-itim
    facebook: john.andrew.patricio
    instagram: johnandrew.sp
    avatar: assets/images/vinny-avatar.jpg
    card-cover: assets/images/john-card.jpg
    cover: 'assets/images/groups/team-itim/vinny-cover.jpg'
    occupation: Software Developer / Test Automation Engineer
    description: "Makes computers do sh*t for a living. Makes music, plays games, rolls on the mats, and cycles for fun. Started cycling in October 2020."
    bikes:
      allez: 
        name: Stella
        make: Specialized
        model: Allez
        year: 2020
        photo: 'assets/images/stella.jpg'
        description: 'Shimano 105, RS11, GP5000 25c'
        status: operational
  jayvonn:
    name: jayvonn-vargas
    display_name: Jay Vonn Vargas
    nickname: Jay Vonn
    role: contributor
    showProfile: false
    team: team-itim
    facebook: vargas.jayvonn
    instagram: jebiboy
    avatar: assets/images/vinny-avatar.jpg
    card-cover: assets/images/jayvonn-card.jpg
    cover: 'assets/images/groups/team-itim/vinny-cover.jpg'
    occupation: Software Developer / Test Automation Engineer
    description: "Makes computers do sh*t for a living. Makes music, plays games, rolls on the mats, and cycles for fun. Started cycling in October 2020."
    bikes:
      allez: 
        name: Stella
        make: Specialized
        model: Allez
        year: 2020
        photo: 'assets/images/stella.jpg'
        description: 'Shimano 105, RS11, GP5000 25c'
        status: operational
  dee:
    name: dee-marquez
    display_name: Dee Marquez
    role: author
    showProfile: false
    team: misis-ride
    avatar: 'assets/images/dee-avatar.jpg'
    cover: 'assets/images/groups/team-itim/vinny-cover.jpg'
    email: latebloomercycling@gmail.com
    description: "Quasi-cyclist, flower gatherer, dog spotter, fickle gear chooser, and silken tofu hunter. Started biking (for reals) March 2021."
    bikes:
      allez: 
        name: Yuba
        make: GT
        model: Zaskar
        year: 2004
        photo: 'assets/images/stella.jpg'
        description: 'Resto-mod. SRAM SX. White Shimano M445 brakeset. The Project Loopbar. Teal powdercoat.'
        status: operational
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true
  hard_wrap: true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
