lang: en-US
title: Late Bloomer Cycling
email: latebloomercycling@gmail.com
description: "Your new default Jekyll theme"
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://chuv13.github.io/"  # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: Vinny Marquez
  twitter: Towlette_Pettetucci
  picture: /assets/images/johndoe.png
twitter_username: latebloomercycling
github_username: latebloomercycling
logo: /assets/icons/light-logo.svg
search: true
search_full_content: true
search_provider: algolia
algolia:
  application_id: QB6HVGBSBA
  index_name: basically-basic
  search_only_api_key: 9d5014e5bbc77372547bce778dfa5663
  powered_by: # true (default), false

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
# remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
plugins: # previsously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Exclude from processing.
exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - .scss-lint.yml
  - CHANGELOG
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - Rakefile
  - README
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - /docs # ignore Basically Basic sample site
  - /example # ignore Basically Basic dev site

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
